### ISSUE TITLE
Create Lists that must meet all Genre selected

### ISSUE THREAD

**Issue by spoonys** [TheUltimateC0der/listrr.pro#54]
For example, Crime and Thriller to get Crime Thrillers

**Comment by FrostyWolf** [comment]
This is always a fun one from a UI perspective.

![image](https://user-images.githubusercontent.com/2111744/74597202-f5bdec00-5028-11ea-9957-7dd3f57be944.png)

Plex has a interesting way of handling it that adds a lot of flexibility to sorting.

**Comment by scadden365** [comment]
Looking for the same feature, ran query for Adventure Documentaries, getting all Adventure movie.

**Comment by sitkonen** [comment]
I am also looking for this feature. Crime + Documentaries = Crime Documentaries, not Crime or Documentaries.

**Comment by TheUltimateC0der** [comment]
This is fixed in V2. Come to the discord linked in the readme, and write me a PM to get access to test it out.
